// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yoqzbdctvgnfkrleehzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvcXpiZGN0dmduZmtybGVlaHprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM4NDE2ODksImV4cCI6MjA4OTQxNzY4OX0.Lb9nfLUza_lWKXm_Q23h8vkRnOg5MUs0VjfsKQwmVaU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});